---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: andrewbruce-net
  labels:
    app: andrewbruce-net
spec:
  selector:
    matchLabels:
      app: andrewbruce-net
  template:
    metadata:
      labels:
        app: andrewbruce-net
    spec:
      containers:
      - name: andrewbruce-net
        image: $IMAGE
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP

        readinessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2

        livenessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
